/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ftdi_D2xx */

#ifndef _Included_com_ftdi_D2xx
#define _Included_com_ftdi_D2xx
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ftdi_D2xx_FT_OPEN_BY_SERIAL_NUMBER
#define com_ftdi_D2xx_FT_OPEN_BY_SERIAL_NUMBER 1L
#undef com_ftdi_D2xx_FT_OPEN_BY_DESCRIPTION
#define com_ftdi_D2xx_FT_OPEN_BY_DESCRIPTION 2L
#undef com_ftdi_D2xx_FT_OPEN_BY_LOCATION
#define com_ftdi_D2xx_FT_OPEN_BY_LOCATION 4L
#undef com_ftdi_D2xx_FT_LIST_NUMBER_ONLY
#define com_ftdi_D2xx_FT_LIST_NUMBER_ONLY -2147483648L
#undef com_ftdi_D2xx_FT_LIST_BY_INDEX
#define com_ftdi_D2xx_FT_LIST_BY_INDEX 1073741824L
#undef com_ftdi_D2xx_FT_LIST_ALL
#define com_ftdi_D2xx_FT_LIST_ALL 536870912L
#undef com_ftdi_D2xx_FT_DATA_BITS_7
#define com_ftdi_D2xx_FT_DATA_BITS_7 7L
#undef com_ftdi_D2xx_FT_DATA_BITS_8
#define com_ftdi_D2xx_FT_DATA_BITS_8 8L
#undef com_ftdi_D2xx_FT_STOP_BITS_1
#define com_ftdi_D2xx_FT_STOP_BITS_1 0L
#undef com_ftdi_D2xx_FT_STOP_BITS_2
#define com_ftdi_D2xx_FT_STOP_BITS_2 2L
#undef com_ftdi_D2xx_FT_PARITY_NONE
#define com_ftdi_D2xx_FT_PARITY_NONE 0L
#undef com_ftdi_D2xx_FT_PARITY_ODD
#define com_ftdi_D2xx_FT_PARITY_ODD 1L
#undef com_ftdi_D2xx_FT_PARITY_EVEN
#define com_ftdi_D2xx_FT_PARITY_EVEN 2L
#undef com_ftdi_D2xx_FT_PARITY_MARK
#define com_ftdi_D2xx_FT_PARITY_MARK 3L
#undef com_ftdi_D2xx_FT_PARITY_SPACE
#define com_ftdi_D2xx_FT_PARITY_SPACE 4L
#undef com_ftdi_D2xx_FT_FLOW_NONE
#define com_ftdi_D2xx_FT_FLOW_NONE 0L
#undef com_ftdi_D2xx_FT_FLOW_RTS_CTS
#define com_ftdi_D2xx_FT_FLOW_RTS_CTS 256L
#undef com_ftdi_D2xx_FT_FLOW_DTR_DSR
#define com_ftdi_D2xx_FT_FLOW_DTR_DSR 512L
#undef com_ftdi_D2xx_FT_FLOW_XON_XOFF
#define com_ftdi_D2xx_FT_FLOW_XON_XOFF 1024L
#undef com_ftdi_D2xx_FT_PURGE_RX
#define com_ftdi_D2xx_FT_PURGE_RX 1L
#undef com_ftdi_D2xx_FT_PURGE_TX
#define com_ftdi_D2xx_FT_PURGE_TX 2L
#undef com_ftdi_D2xx_FT_CTS
#define com_ftdi_D2xx_FT_CTS 16L
#undef com_ftdi_D2xx_FT_DSR
#define com_ftdi_D2xx_FT_DSR 32L
#undef com_ftdi_D2xx_FT_RI
#define com_ftdi_D2xx_FT_RI 64L
#undef com_ftdi_D2xx_FT_DCD
#define com_ftdi_D2xx_FT_DCD -128L
#undef com_ftdi_D2xx_FT_OE
#define com_ftdi_D2xx_FT_OE 2L
#undef com_ftdi_D2xx_FT_PE
#define com_ftdi_D2xx_FT_PE 4L
#undef com_ftdi_D2xx_FT_FE
#define com_ftdi_D2xx_FT_FE 8L
#undef com_ftdi_D2xx_FT_BI
#define com_ftdi_D2xx_FT_BI 16L
#undef com_ftdi_D2xx_FT_EVENT_RXCHAR
#define com_ftdi_D2xx_FT_EVENT_RXCHAR 1L
#undef com_ftdi_D2xx_FT_EVENT_MODEM_STATUS
#define com_ftdi_D2xx_FT_EVENT_MODEM_STATUS 2L
#undef com_ftdi_D2xx_FT_EVENT_LINE_STATUS
#define com_ftdi_D2xx_FT_EVENT_LINE_STATUS 4L
#undef com_ftdi_D2xx_FT_FLAGS_OPENED
#define com_ftdi_D2xx_FT_FLAGS_OPENED 1L
#undef com_ftdi_D2xx_FT_FLAGS_HI_SPEED
#define com_ftdi_D2xx_FT_FLAGS_HI_SPEED 2L
#undef com_ftdi_D2xx_FT_DEVICE_232B
#define com_ftdi_D2xx_FT_DEVICE_232B 0L
#undef com_ftdi_D2xx_FT_DEVICE_8U232AM
#define com_ftdi_D2xx_FT_DEVICE_8U232AM 1L
#undef com_ftdi_D2xx_FT_DEVICE_8U100AX
#define com_ftdi_D2xx_FT_DEVICE_8U100AX 2L
#undef com_ftdi_D2xx_FT_DEVICE_UNKNOWN
#define com_ftdi_D2xx_FT_DEVICE_UNKNOWN 3L
#undef com_ftdi_D2xx_FT_DEVICE_2232
#define com_ftdi_D2xx_FT_DEVICE_2232 4L
#undef com_ftdi_D2xx_FT_DEVICE_232R
#define com_ftdi_D2xx_FT_DEVICE_232R 5L
#undef com_ftdi_D2xx_FT_DEVICE_2232H
#define com_ftdi_D2xx_FT_DEVICE_2232H 6L
#undef com_ftdi_D2xx_FT_DEVICE_4232H
#define com_ftdi_D2xx_FT_DEVICE_4232H 7L
#undef com_ftdi_D2xx_FT_DEVICE_232H
#define com_ftdi_D2xx_FT_DEVICE_232H 8L
#undef com_ftdi_D2xx_FT_BITMODE_RESET
#define com_ftdi_D2xx_FT_BITMODE_RESET 0L
#undef com_ftdi_D2xx_FT_BITMODE_ASYNC_BITBANG
#define com_ftdi_D2xx_FT_BITMODE_ASYNC_BITBANG 1L
#undef com_ftdi_D2xx_FT_BITMODE_MPSSE
#define com_ftdi_D2xx_FT_BITMODE_MPSSE 2L
#undef com_ftdi_D2xx_FT_BITMODE_SYNC_BITBANG
#define com_ftdi_D2xx_FT_BITMODE_SYNC_BITBANG 4L
#undef com_ftdi_D2xx_FT_BITMODE_MCU_HOST
#define com_ftdi_D2xx_FT_BITMODE_MCU_HOST 8L
#undef com_ftdi_D2xx_FT_BITMODE_FAST_SERIAL
#define com_ftdi_D2xx_FT_BITMODE_FAST_SERIAL 16L
#undef com_ftdi_D2xx_FT_BITMODE_CBUS_BITBANG
#define com_ftdi_D2xx_FT_BITMODE_CBUS_BITBANG 32L
#undef com_ftdi_D2xx_FT_BITMODE_SYNC_FIFO
#define com_ftdi_D2xx_FT_BITMODE_SYNC_FIFO 64L
#undef com_ftdi_D2xx_FT_232R_CBUS_TXDEN
#define com_ftdi_D2xx_FT_232R_CBUS_TXDEN 0L
#undef com_ftdi_D2xx_FT_232R_CBUS_PWRON
#define com_ftdi_D2xx_FT_232R_CBUS_PWRON 1L
#undef com_ftdi_D2xx_FT_232R_CBUS_RXLED
#define com_ftdi_D2xx_FT_232R_CBUS_RXLED 2L
#undef com_ftdi_D2xx_FT_232R_CBUS_TXLED
#define com_ftdi_D2xx_FT_232R_CBUS_TXLED 3L
#undef com_ftdi_D2xx_FT_232R_CBUS_TXRXLED
#define com_ftdi_D2xx_FT_232R_CBUS_TXRXLED 4L
#undef com_ftdi_D2xx_FT_232R_CBUS_SLEEP
#define com_ftdi_D2xx_FT_232R_CBUS_SLEEP 5L
#undef com_ftdi_D2xx_FT_232R_CBUS_CLK48
#define com_ftdi_D2xx_FT_232R_CBUS_CLK48 6L
#undef com_ftdi_D2xx_FT_232R_CBUS_CLK24
#define com_ftdi_D2xx_FT_232R_CBUS_CLK24 7L
#undef com_ftdi_D2xx_FT_232R_CBUS_CLK12
#define com_ftdi_D2xx_FT_232R_CBUS_CLK12 8L
#undef com_ftdi_D2xx_FT_232R_CBUS_CLK6
#define com_ftdi_D2xx_FT_232R_CBUS_CLK6 9L
#undef com_ftdi_D2xx_FT_232R_CBUS_IOMODE
#define com_ftdi_D2xx_FT_232R_CBUS_IOMODE 10L
#undef com_ftdi_D2xx_FT_232R_CBUS_BITBANG_WR
#define com_ftdi_D2xx_FT_232R_CBUS_BITBANG_WR 11L
#undef com_ftdi_D2xx_FT_232R_CBUS_BITBANG_RD
#define com_ftdi_D2xx_FT_232R_CBUS_BITBANG_RD 12L
#undef com_ftdi_D2xx_FT_232H_CBUS_TRISTATE
#define com_ftdi_D2xx_FT_232H_CBUS_TRISTATE 0L
#undef com_ftdi_D2xx_FT_232H_CBUS_RXLED
#define com_ftdi_D2xx_FT_232H_CBUS_RXLED 1L
#undef com_ftdi_D2xx_FT_232H_CBUS_TXLED
#define com_ftdi_D2xx_FT_232H_CBUS_TXLED 2L
#undef com_ftdi_D2xx_FT_232H_CBUS_TXRXLED
#define com_ftdi_D2xx_FT_232H_CBUS_TXRXLED 3L
#undef com_ftdi_D2xx_FT_232H_CBUS_PWREN
#define com_ftdi_D2xx_FT_232H_CBUS_PWREN 4L
#undef com_ftdi_D2xx_FT_232H_CBUS_SLEEP
#define com_ftdi_D2xx_FT_232H_CBUS_SLEEP 5L
#undef com_ftdi_D2xx_FT_232H_CBUS_DRIVE_0
#define com_ftdi_D2xx_FT_232H_CBUS_DRIVE_0 6L
#undef com_ftdi_D2xx_FT_232H_CBUS_DRIVE_1
#define com_ftdi_D2xx_FT_232H_CBUS_DRIVE_1 7L
#undef com_ftdi_D2xx_FT_232H_CBUS_IOMODE
#define com_ftdi_D2xx_FT_232H_CBUS_IOMODE 8L
#undef com_ftdi_D2xx_FT_232H_CBUS_TXDEN
#define com_ftdi_D2xx_FT_232H_CBUS_TXDEN 9L
#undef com_ftdi_D2xx_FT_232H_CBUS_CLK30
#define com_ftdi_D2xx_FT_232H_CBUS_CLK30 10L
#undef com_ftdi_D2xx_FT_232H_CBUS_CLK15
#define com_ftdi_D2xx_FT_232H_CBUS_CLK15 11L
#undef com_ftdi_D2xx_FT_232H_CBUS_CLK7_5
#define com_ftdi_D2xx_FT_232H_CBUS_CLK7_5 12L
#undef com_ftdi_D2xx_FT_DRIVE_CURRENT_4MA
#define com_ftdi_D2xx_FT_DRIVE_CURRENT_4MA 4L
#undef com_ftdi_D2xx_FT_DRIVE_CURRENT_8MA
#define com_ftdi_D2xx_FT_DRIVE_CURRENT_8MA 8L
#undef com_ftdi_D2xx_FT_DRIVE_CURRENT_12MA
#define com_ftdi_D2xx_FT_DRIVE_CURRENT_12MA 12L
#undef com_ftdi_D2xx_FT_DRIVE_CURRENT_16MA
#define com_ftdi_D2xx_FT_DRIVE_CURRENT_16MA 16L
/*
 * Class:     com_ftdi_D2xx
 * Method:    setVIDPID
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setVIDPID
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getVIDPID
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_ftdi_D2xx_getVIDPID
  (JNIEnv *, jclass);

/*
 * Class:     com_ftdi_D2xx
 * Method:    createDeviceInfoList
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_createDeviceInfoList
  (JNIEnv *, jclass);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getDeviceInfoList
 * Signature: (I[Lcom/ftdi/D2xx/FtDeviceInfoListNode;)I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_getDeviceInfoList
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getDeviceInfoListDetail
 * Signature: (I)Lcom/ftdi/D2xx/FtDeviceInfoListNode;
 */
JNIEXPORT jobject JNICALL Java_com_ftdi_D2xx_getDeviceInfoListDetail
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getLibraryVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_getLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_ftdi_D2xx
 * Method:    openByIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_openByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    openBySerialNumber
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_openBySerialNumber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ftdi_D2xx
 * Method:    openByDescription
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_openByDescription
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ftdi_D2xx
 * Method:    openByLocation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_openByLocation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_close
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    read
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_read
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setBaudRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setBaudRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setDataCharacteristics
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setDataCharacteristics
  (JNIEnv *, jobject, jbyte, jbyte, jbyte);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setFlowControl
 * Signature: (SBB)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setFlowControl
  (JNIEnv *, jobject, jshort, jbyte, jbyte);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setTimeouts
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setTimeouts
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setDtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setDtr
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    clrDtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_clrDtr
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setRts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setRts
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    clrRts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_clrRts
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setBreakOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setBreakOn
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setBreakOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setBreakOff
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getModemStatus
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ftdi_D2xx_getModemStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getQueueStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_getQueueStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getStatus
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_ftdi_D2xx_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    purge
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_purge
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_ftdi_D2xx
 * Method:    resetDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_resetDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    stopInTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_stopInTask
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    restartInTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_restartInTask
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getDeviceInfo
 * Signature: ()Lcom/ftdi/D2xx/FtDeviceInfoListNode;
 */
JNIEXPORT jobject JNICALL Java_com_ftdi_D2xx_getDeviceInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setChars
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setChars
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setUSBParameters
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setUSBParameters
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getDriverVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_getDriverVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setEventNotification
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setEventNotification
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    waitEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_waitEvent
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    waitEventTimed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ftdi_D2xx_waitEventTimed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setLatencyTimer
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setLatencyTimer
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getLatencyTimer
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_ftdi_D2xx_getLatencyTimer
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    setBitMode
 * Signature: (BB)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_setBitMode
  (JNIEnv *, jobject, jbyte, jbyte);

/*
 * Class:     com_ftdi_D2xx
 * Method:    getPinStates
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_ftdi_D2xx_getPinStates
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromReadWord
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_ftdi_D2xx_eepromReadWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromWriteWord
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_eepromWriteWord
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromErase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_eepromErase
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromRead
 * Signature: ()Lcom/ftdi/D2xx/FtProgramData;
 */
JNIEXPORT jobject JNICALL Java_com_ftdi_D2xx_eepromRead
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromWrite
 * Signature: (Lcom/ftdi/D2xx/FtProgramData;)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_eepromWrite
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromGetUserAreaSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ftdi_D2xx_eepromGetUserAreaSize
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromReadUserArea
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ftdi_D2xx_eepromReadUserArea
  (JNIEnv *, jobject);

/*
 * Class:     com_ftdi_D2xx
 * Method:    eepromWriteUserArea
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_ftdi_D2xx_eepromWriteUserArea
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
