/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ftdi_D2xx_FtDeviceInfoListNode */

#ifndef _Included_com_ftdi_D2xx_FtDeviceInfoListNode
#define _Included_com_ftdi_D2xx_FtDeviceInfoListNode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
